name: "Auto Merge Dependabot Updates"
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check update type
        run: echo "Update type: ${{ steps.metadata.outputs.update-type }}"

      - name: Auto-merge Dependabot PRs for minor and patch updates
        if: contains(fromJSON('["version-update:semver-minor", "version-update:semver-patch"]'), steps.metadata.outputs.update-type)
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Merging PR: $PR_URL"
          gh pr merge --auto --merge "$PR_URL"

      - name: Notify failure
        if: failure()
        run: echo "Auto-merge failed. Check PR status and logs."
