name: PHPStan Static Analysis

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan-analysis.yml'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan-analysis.yml'

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-dist"

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
