name: Qodana Code Quality Scan

on:
  push:

permissions:
  contents: read

jobs:
  qodana:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Qodana
        uses: actions/cache@v3
        with:
          path: ~/.qodana
          key: qodana-${{ runner.os }}-${{ github.sha }}
          restore-keys: qodana-${{ runner.os }}-

      - name: Qodana Scan
        uses: JetBrains/qodana-action@latest
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        continue-on-error: true

      - name: Notify on Failure
        if: failure()
        run: echo "Qodana scan detected issues. Please review the logs."
